### ISSUE TITLE
7zdec usage requires 7zpass

### ISSUE THREAD

**Issue by zcream** [d99kris/7zetools#2]
I have the 7zdec executable and I attempted to extract ffmpeg.7z - I got the message 
`Password is not set, please run 7zpass to set password`

However, I am able to use the compiled 7zdec directly from 7z.org without this requirement.
What is the default encryption key, and is there a way to extract without this key ?

**Comment by d99kris** [comment]
Hi! I am not familiar with other utils named `7zdec` - not sure if the link you shared is correct (it looks like ads / a parking page).

Anyway, `7zetools` is not really a replacement for standard `7z`, it's more of a complement in form of wrapper scripts for `7z` - intended only for working with **encrypted** 7z archives. If your 7z archive is not encrypted it's better to use the standard 7z tool (the `7zetools` will not work).

I will close this issue, but feel free to re-open if you have follow-up questions.
